"""Change hourly_rate from employee to salary

Revision ID: e8a1aaf43b61
Revises: 
Create Date: 2025-03-12 11:00:37.163378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a1aaf43b61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hourly_rate')
    op.add_column('salaries', sa.Column('monthly_income', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('salaries', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.drop_column('salaries', 'salary_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('salary_amount', sa.FLOAT(), nullable=False))
    op.drop_column('salaries', 'hourly_rate')
    op.drop_column('salaries', 'monthly_income')
    op.add_column('employees', sa.Column('hourly_rate', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
